Ana cli arguments
rom-melnyk/rota_pattern pull request #1
Opened 2019-12-25 17:43 UTC by MethewsMuller

2019-12-27 10:06 UTC, rom-melnyk requested changes

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +	bool SetDout(int dout) { this->dout = dout; return 1; }
1. Nice implementation of encapsulation principle: there are _private data_ and _public getters/setters._
1. // _Minor:_ `bool` &rarr; `void`. Not sure if we need return value here.
1. `1` is not `bool` however it can  be casted to `bool` 😃. Please be as strict as possible with typing; it helps a lot in early error detection.

Another question: is there a common practice to use CapitalizedMethodName-s?

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +	CLIarguments(int dout = 0, int din = 0, int pen = 0) { //def constructor
Do we expect to call the constructor with parameters in order to set default values?
Or can we set default values to `0` right in the constructor or even in `:9-11`?

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +	void Parsing(char *arg) {
// _Minor:_ there is common practice for method or function naming: it should be _a verb._ Why? — because it _does something_ so it sounds logical to use verb for describing that.
That improves further code readability. If you doubt it just imagine how your further code will look like. **If you can _human_ can read it as a novel it's good.**

More here:
- If function/method returns some value it makes sense to name it like `GetThatValue()` or `FindThatValue()` or something like that. Check out your getters.
- If function/method returns `bool` it makes sense to name it according to _appropriate attribution_ e.g., `HasMoreArguments()` or `IsLastOption()`. Think `if (HasMoreArguments()) { arg = GetNextArgument(); }`.
- If function/method is a `void` one it makes sense to use common verb like `Parse()`.

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +		int size = strlen(arg) + 1;
`+ 1` is in order to count in the very last `\0` (null-byte terminator), right?

2019-12-27 10:06 UTC, rom-melnyk commented on src/rota_pattern.cpp
> +	abc.Parsing(argum[3]);
What if there are more that three or  less than three arguments?

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +		p--;
Why? Looks like the variable is not used after this line.

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +		int j = 0, a = 0, p = 0;  //iterators or counters
Semantic (human-readable) names would help:

- `buff` &rarr; `strippedArgument` or `argumentWithoutControlChars` or `alphaNumericChars` or something like that;
- `j` &rarr; `%prevous_variable_name%Index`;
- `a` &rarr; `numberPartIndex`;
- `p` &rarr; `namePartIndex`.

Your names might be different of course but please keep readability for human in mind: why `numberPart[a]` but not `numberPart[p]`? What's the difference between `a` and `p`?

2019-12-27 10:06 UTC, rom-melnyk commented on src/cli_arguments.h
> +		delete[]namePart;
// _minor:_ space missed.

2019-12-27 10:06 UTC, rom-melnyk commented on src/rota_pattern.cpp
> +	CLIarguments abc;
Please use semantic self-describing variable name.

2019-12-28 06:38 UTC, MethewsMuller commented on src/cli_arguments.h
> +		int size = strlen(arg) + 1;
yup, your right

2019-12-30 14:36 UTC, rom-melnyk approved these changes

2019-12-30 14:36 UTC, merged